### ISSUE TITLE
How to use the built boxes?

### ISSUE THREAD

**Issue by debovema** [ringods/xenserver-images#1]
Hi,

I succeeded to build a Vagrant box with Packer for XenServer 7.2.
I did a *vagrant up* with this box and it seems to boot.

However the *vagrant ssh* is not working.
I also tried using the VirtualBox console where I can access the Xen console but I don't know the default credentials (for root user).

Any hint ?

Thanks

**Comment by ringods** [comment]
That's weird. If you built the Xenserver image, it installed the shared Vagrant ssh keypair. You should not need to know a password. Can you provide me a vagrant debug log file as a Github gist?

https://www.vagrantup.com/docs/other/debugging.html

**Comment by debovema** [comment]
I had a further look and it turned out that the problem was caused by my Shell.

I tried with
* Babun (cygwin) : KO
* MinGW (from Git for Windows) : KO
* cmd.exe : OK

By running the *vagrant ssh* command with *--debug* switch I can retrieve the full command-line to use in Babun. That is strange because I can do *vagrant ssh* on other boxes in Babun.

Thanks for your time.
